/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2025-08-20 14:03:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section style=\"position: fixed; top: 200px; left: 0px; width: 100%; height: 100%; background-color: lightgray;\">\r\n");
      out.write("<h2 style=\"text-align: center;\">수강신청</h2>\r\n");
      out.write("\r\n");
      out.write("<form action=\"action.jsp\" name=\"frm\" style=\"display:flex; align-items:center; justify-content:center;\">\r\n");
      out.write("\t<table style=\"width: 500px;\" border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;\">수강월</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"regist_month\"> 예) 2022년03월 -> 202203</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;\">회원명</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select style=\"width: 175px;\" name=\"c_name\" onchange=\"aa(this.value)\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">회원명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10001\">홍길동</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10002\">장발장</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10003\">임꺽정</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"20001\">성춘향</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"20002\">이몽룡</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;\">회원번호</td>\r\n");
      out.write("\t\t\t<td><input id=\"c_no\" name=\"c_no\" readonly> 예) 10001</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;\">강의 장소</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"class_area\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;\">강의명</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select style=\"width: 175px;\" name=\"class_name\" onchange=\"bb(this.value)\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">강의신청</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"100000\">초급반</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"200000\">중급반</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"300000\">고급반</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"400000\">심화반</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"text-align: center;\">수강료</td>\r\n");
      out.write("\t\t\t<td><input id=\"tuition\" name=\"tuition\" readonly> 원</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr style=\"text-align: center;\">\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"수강신청\" onclick=\"add()\"> &nbsp;\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"다시쓰기\" onclick=\"res()\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction add() {\r\n");
      out.write("\t\tif(frm.regist_month.value == 0) {\r\n");
      out.write("\t\t\talert('수강월이 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tfrm.regist_month.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(frm.c_name.value == 0) {\r\n");
      out.write("\t\t\talert('회원명이 선택되지 않았습니다!');\r\n");
      out.write("\t\t\tfrm.c_name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(frm.class_area.value == 0) {\r\n");
      out.write("\t\t\talert('강의장소가 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tfrm.class_area.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if(frm.class_name.value == 0) {\r\n");
      out.write("\t\t\talert('강의명이 선택되지 않았습니다!');\r\n");
      out.write("\t\t\tfrm.class_name.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert('수강신청이 정상적으로 완료되었습니다!');\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction res() {\r\n");
      out.write("\t\talert('모든 정보를 지우고 처음부터 다시 입력합니다!');\r\n");
      out.write("\t\tdocument.frm.reset();\r\n");
      out.write("\t\tfrm.regist_month.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction aa(c_no) {\r\n");
      out.write("\t\tdocument.getElementById(\"c_no\").value = c_no;\r\n");
      out.write("\t\tc = c_no;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction bb(tuition) {\r\n");
      out.write("\t\tif(c >= 20000)\r\n");
      out.write("\t\t\tdocument.getElementById(\"tuition\").value = tuition/2;\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tdocument.getElementById(\"tuition\").value = tuition;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
