/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2025-08-12 06:12:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section style=\"position: fixed; top: 230px; left: 0px; width: 100%; height: 100%; background-color: lightgray;\">\r\n");
      out.write("<h2 style=\"text-align: center; padding-top: 50px;\">검사결과입력</h2>\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"action.jsp\" name = \"frm\" style = \"display: flex; aligns-item: center; justify-content: center;\">\r\n");
      out.write("\t<table border = \"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style =\"text-align: center;\">환자번호</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"p_no\"> 예)1001</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style =\"text-align: center;\">검사코드</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select name=\"t_code\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">검사명</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"t001\">[T001]결핵</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"t002\">[T002]장티푸스</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"t003\">[T003]수두</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"t004\">[T004]홍역</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"t005\">[T005]콜레라</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style =\"text-align: center;\">검사시작일자</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"t_sdate\"> 예)20200101</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style =\"text-align: center;\">검사상태</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"t_status\" value=\"1\">검사중\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"t_status\" value=\"2\">검사완료\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style =\"text-align: center;\">검사완료일자</td>\r\n");
      out.write("\t\t\t<td><input type = \"text\" name = \"t_ldate\"> 예)20200101</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style =\"text-align: center;\">검사결과</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"t_result\" value=\"X\">미입력\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"t_result\" value=\"P\">양성\r\n");
      out.write("\t\t\t\t<input type = \"radio\" name = \"t_result\" value=\"N\">음성\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style =\"text-align: center;\" colspan = \"2\">\r\n");
      out.write("\t\t\t\t<input type = \"button\" value = \"검사결과등록\" onclick=\"add()\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input type = \"button\" value = \"다시쓰기\" onclick=\"res()\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction add(){\r\n");
      out.write("\t\tif(frm.p_no.value == 0) {\r\n");
      out.write("\t\t\talert(\"환자번호가 입력되지 않았습니다!\");\r\n");
      out.write("\t\t\tfrm.p_no.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(frm.t_code.value == 0) {\r\n");
      out.write("\t\t\talert(\"검사코드가 선택되지 않았습니다!\");\r\n");
      out.write("\t\t\tfrm.t_code.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(frm.t_sdate.value == 0) {\r\n");
      out.write("\t\t\talert(\"검사시작일자가 입력되지 않았습니다!\");\r\n");
      out.write("\t\t\tfrm.t_sdate.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(frm.t_status.value == 0) {\r\n");
      out.write("\t\t\talert(\"검사상태가 선택되지 않았습니다!\");\r\n");
      out.write("\t\t\tfrm.t_status.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(frm.t_ldate.value == 0) {\r\n");
      out.write("\t\t\talert(\"검사완료일자가 입력되지 않았습니다!\");\r\n");
      out.write("\t\t\tfrm.t_ldate.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(frm.t_result.value == 0) {\r\n");
      out.write("\t\t\talert(\"검사결과가 선택되지 않았습니다!\");\r\n");
      out.write("\t\t\tfrm.t_result.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\talert(\"검사결과가 정상적으로 등록되었습니다\");\r\n");
      out.write("\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction res() {\r\n");
      out.write("\t\talert(\"정보를 지우고 처음부터 다시 입력합니다!\");\r\n");
      out.write("\t\tdocument.frm.reset();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
