/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2025-08-07 08:03:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class rlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/db.jsp", Long.valueOf(1753344138347L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Class.forName("oracle.jdbc.OracleDriver");
Connection con = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xe", "system", "1234");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>rlist</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section style=\"position:fixed; top:70px; width:100%; height:100%; background-color:lightgray;\">\r\n");
      out.write("<h2 style=\"text-align:center;\">검사결과조회</h2>\r\n");
      out.write("<form style=\"display:flex; align-items:center; justify-content:center;\">\r\n");
      out.write("   <table border=\"1\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <th>환자번호</th>\r\n");
      out.write("         <th>환자명</th>\r\n");
      out.write("         <th>검사명</th>\r\n");
      out.write("         <th>검사시작일</th>\r\n");
      out.write("         <th>검사상태</th>\r\n");
      out.write("         <th>검사종료일</th>\r\n");
      out.write("         <th>검사결과</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");

      request.setCharacterEncoding("UTF-8");
      
      try {
         String sql = "SELECT P.P_NO, " + 
                            "P.P_NAME, " + 
                            "L.T_NAME, " + 
                            "P.T_SDATE, " + 
                            "P.T_STATUS, " +
                            "P.T_LDATE, " + 
                            "P.T_RESULT " + 
                            "FROM TBL_RESULT_202004 R " + 
                            "JOIN TBL_PATIENT_202004 P ON R.P_NO = P.P_NO " + 
                            "JOIN TBL_LAB_TEST_202004 L ON R.T_CODE = L.T_CODE " + 
                            "ORDER BY P.P_NO asc";
         PreparedStatement pstmt = con.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery();
         while(rs.next()){
            String pno = rs.getString(1);
            String pnm = rs.getString(2);
            String tnm = rs.getString(3);
            
            String tsd = rs.getString(4);
            String sd = tsd.substring(0, 4) + " - " + tsd.substring(4, 6) + " - " + tsd.substring(6, 8);
            
            String tstat = rs.getString(5);
            if(tstat.equals("1"))
               tstat = "검사중";
            else 
               tstat = "검사완료";
            
            String tld = rs.getString(6);
            String ld = tld.substring(0, 4) + " - " + tld.substring(4, 6) + " - " + tld.substring(6, 8);
            
            String trs = rs.getString(7);
            if(trs.equals("X"))
               trs = "미입력";
               else if (trs.equals("P"))
                  trs = "양성";
               else 
                  trs = "음성";
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>");
      out.print(pno );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(pnm );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(tnm );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(sd );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(tstat );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(ld );
      out.write("</td>\r\n");
      out.write("               <td>");
      out.print(trs );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

         }
         
      } catch(Exception e){
         e.getStackTrace();
      }
      
      out.write("\r\n");
      out.write("   </table>\r\n");
      out.write("</form>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
