/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2025-08-07 06:35:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/db.jsp", Long.valueOf(1753344138347L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Class.forName("oracle.jdbc.OracleDriver");
Connection con = DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/xe", "system", "1234");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section style=\"position: fixed; top: 230px; left: 0px; width: 100%; height: 100%; background-color: lightgray;\">\r\n");
      out.write("<h2 style=\"text-align: center; padding-top: 50px;\">학생성적</h2>\r\n");
      out.write("\r\n");
      out.write("<form style=\"display:flex; aligns-item:center; justify-content:center; text-align:center;\">\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>학년</th>\r\n");
      out.write("\t\t\t<th>반</th>\r\n");
      out.write("\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>국어</th>\r\n");
      out.write("\t\t\t<th>수학</th>\r\n");
      out.write("\t\t\t<th>영어</th>\r\n");
      out.write("\t\t\t<th>역사</th>\r\n");
      out.write("\t\t\t<th>합계</th>\r\n");
      out.write("\t\t\t<th>평균</th>\r\n");
      out.write("\t\t\t<th>석차</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		request.setCharacterEncoding("UTF-8");
		int rank = 1;
		int sumk = 0;
		int summ = 0;
		int sume = 0;
		int sumh = 0;
		int sumt = 0;
		double suma = 0;
		try {
			String sql = "select s.sno, sname, ekor, emath, eeng, ehist, ekor+emath+eeng+ehist as total, round((ekor+emath+eeng+ehist)/4.0, 1) as avg "
					+ "from student_tbl_01 s "
					+ "left join exam_tbl_01 e on s.sno = e.sno order by avg desc nulls last, s.sno asc";
			PreparedStatement pstmt = con.prepareStatement(sql);
			ResultSet rs = pstmt.executeQuery();
			while(rs.next()) {
				String sno = rs.getString(1);
				String grade = sno.substring(0,1);
				String group = sno.substring(1,3);
				String number = sno.substring(3,5);
				sumk += rs.getInt(3);
				summ += rs.getInt(4);
				sume += rs.getInt(5);
				sumh += rs.getInt(6);
				sumt += rs.getInt(7);
				suma += rs.getDouble(8);	
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(grade);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(group);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(number);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(3) != null ? rs.getString(3) : "");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(4) != null ? rs.getString(4) : "");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(5) != null ? rs.getString(5) : "");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(6) != null ? rs.getString(6) : "");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(7) != null ? rs.getString(7) : "");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(8) != null ? rs.getString(8) : "");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(rs.getString(8) != null ? rank++ : "");
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\">총　합</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(sumk);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(summ);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(sume);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(sumh);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(sumt);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(suma);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\">총평균</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( (rank > 1) ? Math.round((sumk * 10.0) / (rank - 1)) / 10.0 : 0 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( (rank > 1) ? Math.round((summ * 10.0) / (rank - 1)) / 10.0 : 0 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( (rank > 1) ? Math.round((sume * 10.0) / (rank - 1)) / 10.0 : 0 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( (rank > 1) ? Math.round((sumh * 10.0) / (rank - 1)) / 10.0 : 0 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( (rank > 1) ? Math.round((sumt * 10.0) / (rank - 1)) / 10.0 : 0 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( (rank > 1) ? Math.round((suma * 10.0) / (rank - 1)) / 10.0 : 0 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

		} catch(Exception e) {
			e.printStackTrace();
		}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
